version: '2'

services:

    graphite:
        container_name: trex-graphite-graphite
        image: hopsoft/graphite-statsd
        ports:
           - "8088:80"
           - "2003:2003"
           - "2004:2004"
           - "2023:2023"
           - "2024:2024"
           - "8125:8125"
           - "8126:8126"